#%RAML 1.0
title: stock-movement
version: v1
baseUri: http://api.samplehost.com

/stock-adjustments:
  post:
    body:
      application/xml:
        type: !include schemas/i0809/CDF_StockAdjustment.xsd
        example: !include examples/i0809/i0809-example.xml
    responses:
      202:
